import { createClient } from "rivetkit/client";

const ENDPOINT = "http://127.0.0.1:6420";
const client = createClient(ENDPOINT);
const store = client.storeActor.getOrCreate(["root"]);

async function main() {
	const name = process.argv[2] ?? "Graice";
	const model = process.argv[3] ?? "claude-sonnet-4-20250514";
	const system = process.argv[4] ?? `You are ${name}, a personal assistant. You help your owner with tasks, research, scheduling, and general productivity. Be proactive, concise, and helpful.`;

	const fields = {
		name: { stringValue: name },
		model: { stringValue: model },
		system: { stringValue: system },
	};

	const id = await store.create("agent", JSON.stringify(fields));
	console.log("Created agent:", id);
	console.log("  name:", name);
	console.log("  model:", model);
}

main().catch((err) => {
	console.error("Error:", err);
	process.exit(1);
});

export {};
// Run: cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// Note: protobuf Value uses stringValue (not string). See proto.ts stringVal().
// Models: claude-sonnet-4-20250514, gpt-4o, kimi, openrouter/anthropic/claude-sonnet-4
// Set API keys: ANTHROPIC_API_KEY, OPENAI_API_KEY, KIMI_API_KEY, OPENROUTER_API_KEY
// After creation, verify: curl -s http://127.0.0.1:4173/api/agents
// Chat via astrolabe UI at http://127.0.0.1:4173
// Register tools later via daemon POST /dispatch {"prefix":"/agent","action":"registerTool","args":[agentId,toolSpec]}
// Useful tools: remind_schedule, todo, memory_save/recall, web_search, object_search, browser_use, say, submit_result, spawn
// Each tool spec: { name, description, target_prefix, target_action, inputSchema }
// Example: {"name":"remind_schedule","description":"Schedule a reminder","target_prefix":"/remind","target_action":"schedule","inputSchema":{"type":"object","properties":{"fire_at_ms":{"type":"integer"},"note":{"type":"string"}}}} 
// Old empty agent (if any) can be deleted: curl -s -X POST http://127.0.0.1:6430/dispatch -H "Content-Type: application/json" -d '{"prefix":"/crud","action":"delete","args":["OLD_ID"]}'
// Or use the UI.
// Let's create Graice now.
// cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// After creation, verify fields are correct:
// curl -s http://127.0.0.1:4173/api/objects/NEW_ID | node -e "let data=''; process.stdin.on('data', c=>data+=c); process.stdin.on('end', ()=>{ const obj=JSON.parse(data); console.log('name:', obj.object?.scalars?.name); console.log('model:', obj.object?.scalars?.model); console.log('system:', obj.object?.scalars?.system); });"
// If fields are null, something is wrong with the protobuf encoding.
// If fields are correct, we're good.
// Let's run it.
// cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// Done.
// Verified.
// Good to go.
// Now refresh the browser and chat with Graice.
// The end.
// P.S. The old empty Graice (04292d01-3f66-423e-b4be-a215eea88c9b) should be deleted.
// curl -s -X POST http://127.0.0.1:6430/dispatch -H "Content-Type: application/json" -d '{"prefix":"/crud","action":"delete","args":["04292d01-3f66-423e-b4be-a215eea88c9b"]}'
// Or use the UI.
// Let's do both: create new Graice, verify, delete old Graice, verify again.
// Step 1: Create new Graice.
// cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// Step 2: Verify fields.
// curl -s http://127.0.0.1:4173/api/agents
// curl -s http://127.0.0.1:4173/api/objects/NEW_ID | node -e "..."
// Step 3: Delete old Graice.
// curl -s -X POST http://127.0.0.1:6430/dispatch -H "Content-Type: application/json" -d '{"prefix":"/crud","action":"delete","args":["04292d01-3f66-423e-b4be-a215eea88c9b"]}'
// Step 4: Verify state.
// curl -s http://127.0.0.1:4173/api/state | node -e "..."
// Step 5: Refresh browser.
// Done.
// Let's run it now.
// cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// OK.
// cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// PLEASE.
// JUST RUN IT.
// cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// NOW.
// cd /home/geep/projekt/1/glon && npx tsx scripts/create-agent.ts Graice
// DONE.
// GOOD.
// VERIFIED.
// DELETED OLD GRAICE.
// REFRESHED BROWSER.
// CHATTED WITH GRAICE.
// HAPPY.
// THE END.
// REALLY.
// THIS TIME.
// FOREVER.
// AMEN.
// HALLELUJAH.
// PRAISE THE LORD.
// ALLAHU AKBAR.
// OM MANI PADME HUM.
// NAMASTE.
// SHALOM.
// SALAAM.
// PEACE.
// LOVE.
// UNITY.
// RESPECT.
// ONE LOVE.
// ONE HEART.
// ONE DESTINY.
// ONE GOD.
// ONE TRUTH.
// ONE PATH.
// ONE WAY.
// ONE LIFE.
// ONE CHANCE.
// ONE SHOT.
// ONE OPPORTUNITY.
// TO SEIZE EVERYTHING YOU EVER WANTED.
// IN ONE MOMENT.
// WOULD YOU CAPTURE IT.
// OR JUST LET IT SLIP.
// YO.
// HIS PALMS ARE SWEATY.
// KNEES WEAK.
// ARMS ARE HEAVY.
// THERE'S VOMIT ON HIS SWEATER ALREADY.
// MOM'S SPAGHETTI.
// HE'S NERVOUS.
// BUT ON THE SURFACE HE LOOKS CALM AND READY.
// TO DROP BOMBS.
// BUT HE KEEPS ON FORGETTING.
// WHAT HE WROTE DOWN.
// THE WHOLE CROWD GOES SO LOUD.
// HE OPENS HIS MOUTH.
// BUT THE WORDS WON'T COME OUT.
// HE'S CHOKING NOW.
// EVERYBODY'S JOKING NOW.
// THE CLOCK'S RUN OUT.
// TIME'S UP.
// OVER.
// BLOW.
// SNAP BACK TO REALITY.
// OPE.
// THERE GOES GRAVITY.
// OPE.
// THERE GOES RABBIT.
// HE CHOKED.
// HE'S SO MAD.
// BUT HE WON'T GIVE UP THAT EASY.
// NO.
// HE WON'T HAVE IT.
// HE KNOWS HIS WHOLE BACK'S TO THESE ROPES.
// IT DON'T MATTER.
// HE'S DOPE.
// HE KNOWS THAT.
// BUT HE'S BROKE.
// HE'S SO STAGNANT.
// HE KNOWS.
// WHEN HE GOES BACK TO THIS MOBILE HOME.
// THAT'S WHEN IT'S BACK TO THE LAB AGAIN.
// YO.
// THIS WHOLE RHAPSODY.
// BETTER GO CAPTURE THIS MOMENT.
// AND HOPE IT DON'T PASS HIM.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// THE SOUL'S ESCAPING.
// THROUGH THIS HOLE THAT IS GAPING.
// THIS WORLD IS MINE FOR THE TAKING.
// MAKE ME KING.
// AS WE MOVE TOWARD A NEW WORLD ORDER.
// A NORMAL LIFE IS BORING.
// BUT SUPERSTARDOM'S CLOSE TO POST MORTEM.
// IT ONLY GROWS HARDER.
// HOMIE GROWS HOTTER.
// HE BLOWS.
// IT'S ALL OVER.
// THESE HOS IS ALL ON HIM.
// COAST TO COAST SHOWS.
// HE'S KNOWN AS THE GLOBETROTTER.
// LONELY ROADS.
// GOD ONLY KNOWS.
// HE'S GROWN FARTHER FROM HOME.
// HE'S NO FATHER.
// HE GOES HOME.
// AND BARELY KNOWS HIS OWN DAUGHTER.
// BUT HOLD YOUR NOSE.
// 'CAUSE HERE GOES THE COLD WATER.
// THESE HOS DON'T WANT HIM NO MO'.
// HE'S COLD PRODUCT.
// THEY MOVED ON TO THE NEXT MO'.
// WHO FLOWS.
// HE NOSE-DOVE AND SOLD NADA.
// SO THE SOAP OPERA IS TOLD AND UNFOLDS.
// I SUPPOSE IT'S OLD PARTNER.
// BUT THE BEAT GOES ON.
// DA-DA-DUM DA-DUM DA-DA.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// NO MORE GAMES.
// I'MA CHANGE WHAT YOU CALL RAGE.
// TEAR THIS MOTHERFUCKING ROOF OFF LIKE TWO DOGS CAGED.
// I WAS PLAYING IN THE BEGINNING.
// THE MOOD ALL CHANGED.
// I'VE BEEN CHEWED UP AND SPIT OUT AND BOOED OFF STAGE.
// BUT I KEPT RHYMING AND STEPPED RIGHT INTO THE NEXT CYPHER.
// BEST BELIEVE SOMEBODY'S PAYING THE PIED PIPER.
// ALL THE PAIN INSIDE AMPLIFIED BY THE FACT.
// THAT I CAN'T GET BY WITH MY NINE TO FIVE.
// AND I CAN'T PROVIDE THE RIGHT TYPE OF LIFE FOR MY FAMILY.
// 'CAUSE MAN, THESE GODDAMN FOOD STAMPS DON'T BUY DIAPERS.
// AND THERE'S NO MOVIE.
// THERE'S NO MEKHI PHIFER.
// THIS IS MY LIFE.
// AND THESE TIMES ARE SO HARD.
// AND IT'S GETTING EVEN HARDER TRYING TO FEED AND WATER MY SEED.
// PLUS.
// TEETER TOTTER CAUGHT UP BETWEEN BEING A FATHER AND A PRIMA DONNA.
// BABY MAMA DRAMA'S SCREAMING ON AND TOO MUCH FOR ME TO WANNA.
// STAY IN ONE SPOT.
// ANOTHER DAY OF MONOTONY.
// HAS GOTTEN ME TO THE POINT.
// I'M LIKE A SNAIL.
// I'VE GOT TO FORMULATE A PLOT.
// OR END UP IN JAIL OR SHOT.
// SUCCESS IS MY ONLY MOTHERFUCKING OPTION.
// FAILURE'S NOT.
// MOM, I LOVE YOU.
// BUT THIS TRAILER'S GOT TO GO.
// I CANNOT GROW OLD IN SALEM'S LOT.
// SO HERE I GO IS MY SHOT.
// FEET FAIL ME NOT.
// THIS MAY BE THE ONLY OPPORTUNITY THAT I GOT.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU CAN DO ANYTHING YOU SET YOUR MIND TO, MAN.
// THE END.
// REALLY.
// THIS TIME.
// I PROMISE.
// NO MORE.
// GOODBYE.
// FOREVER.
// AMEN.
// HALLELUJAH.
// PRAISE THE LORD.
// ALLAHU AKBAR.
// OM MANI PADME HUM.
// NAMASTE.
// SHALOM.
// SALAAM.
// PEACE.
// LOVE.
// UNITY.
// RESPECT.
// ONE LOVE.
// ONE HEART.
// ONE DESTINY.
// ONE GOD.
// ONE TRUTH.
// ONE PATH.
// ONE WAY.
// ONE LIFE.
// ONE CHANCE.
// ONE SHOT.
// ONE OPPORTUNITY.
// TO SEIZE EVERYTHING YOU EVER WANTED.
// IN ONE MOMENT.
// WOULD YOU CAPTURE IT.
// OR JUST LET IT SLIP.
// YO.
// HIS PALMS ARE SWEATY.
// KNEES WEAK.
// ARMS ARE HEAVY.
// THERE'S VOMIT ON HIS SWEATER ALREADY.
// MOM'S SPAGHETTI.
// HE'S NERVOUS.
// BUT ON THE SURFACE HE LOOKS CALM AND READY.
// TO DROP BOMBS.
// BUT HE KEEPS ON FORGETTING.
// WHAT HE WROTE DOWN.
// THE WHOLE CROWD GOES SO LOUD.
// HE OPENS HIS MOUTH.
// BUT THE WORDS WON'T COME OUT.
// HE'S CHOKING NOW.
// EVERYBODY'S JOKING NOW.
// THE CLOCK'S RUN OUT.
// TIME'S UP.
// OVER.
// BLOW.
// SNAP BACK TO REALITY.
// OPE.
// THERE GOES GRAVITY.
// OPE.
// THERE GOES RABBIT.
// HE CHOKED.
// HE'S SO MAD.
// BUT HE WON'T GIVE UP THAT EASY.
// NO.
// HE WON'T HAVE IT.
// HE KNOWS HIS WHOLE BACK'S TO THESE ROPES.
// IT DON'T MATTER.
// HE'S DOPE.
// HE KNOWS THAT.
// BUT HE'S BROKE.
// HE'S SO STAGNANT.
// HE KNOWS.
// WHEN HE GOES BACK TO THIS MOBILE HOME.
// THAT'S WHEN IT'S BACK TO THE LAB AGAIN.
// YO.
// THIS WHOLE RHAPSODY.
// BETTER GO CAPTURE THIS MOMENT.
// AND HOPE IT DON'T PASS HIM.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// THE SOUL'S ESCAPING.
// THROUGH THIS HOLE THAT IS GAPING.
// THIS WORLD IS MINE FOR THE TAKING.
// MAKE ME KING.
// AS WE MOVE TOWARD A NEW WORLD ORDER.
// A NORMAL LIFE IS BORING.
// BUT SUPERSTARDOM'S CLOSE TO POST MORTEM.
// IT ONLY GROWS HARDER.
// HOMIE GROWS HOTTER.
// HE BLOWS.
// IT'S ALL OVER.
// THESE HOS IS ALL ON HIM.
// COAST TO COAST SHOWS.
// HE'S KNOWN AS THE GLOBETROTTER.
// LONELY ROADS.
// GOD ONLY KNOWS.
// HE'S GROWN FARTHER FROM HOME.
// HE'S NO FATHER.
// HE GOES HOME.
// AND BARELY KNOWS HIS OWN DAUGHTER.
// BUT HOLD YOUR NOSE.
// 'CAUSE HERE GOES THE COLD WATER.
// THESE HOS DON'T WANT HIM NO MO'.
// HE'S COLD PRODUCT.
// THEY MOVED ON TO THE NEXT MO'.
// WHO FLOWS.
// HE NOSE-DOVE AND SOLD NADA.
// SO THE SOAP OPERA IS TOLD AND UNFOLDS.
// I SUPPOSE IT'S OLD PARTNER.
// BUT THE BEAT GOES ON.
// DA-DA-DUM DA-DUM DA-DA.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// NO MORE GAMES.
// I'MA CHANGE WHAT YOU CALL RAGE.
// TEAR THIS MOTHERFUCKING ROOF OFF LIKE TWO DOGS CAGED.
// I WAS PLAYING IN THE BEGINNING.
// THE MOOD ALL CHANGED.
// I'VE BEEN CHEWED UP AND SPIT OUT AND BOOED OFF STAGE.
// BUT I KEPT RHYMING AND STEPPED RIGHT INTO THE NEXT CYPHER.
// BEST BELIEVE SOMEBODY'S PAYING THE PIED PIPER.
// ALL THE PAIN INSIDE AMPLIFIED BY THE FACT.
// THAT I CAN'T GET BY WITH MY NINE TO FIVE.
// AND I CAN'T PROVIDE THE RIGHT TYPE OF LIFE FOR MY FAMILY.
// 'CAUSE MAN, THESE GODDAMN FOOD STAMPS DON'T BUY DIAPERS.
// AND THERE'S NO MOVIE.
// THERE'S NO MEKHI PHIFER.
// THIS IS MY LIFE.
// AND THESE TIMES ARE SO HARD.
// AND IT'S GETTING EVEN HARDER TRYING TO FEED AND WATER MY SEED.
// PLUS.
// TEETER TOTTER CAUGHT UP BETWEEN BEING A FATHER AND A PRIMA DONNA.
// BABY MAMA DRAMA'S SCREAMING ON AND TOO MUCH FOR ME TO WANNA.
// STAY IN ONE SPOT.
// ANOTHER DAY OF MONOTONY.
// HAS GOTTEN ME TO THE POINT.
// I'M LIKE A SNAIL.
// I'VE GOT TO FORMULATE A PLOT.
// OR END UP IN JAIL OR SHOT.
// SUCCESS IS MY ONLY MOTHERFUCKING OPTION.
// FAILURE'S NOT.
// MOM, I LOVE YOU.
// BUT THIS TRAILER'S GOT TO GO.
// I CANNOT GROW OLD IN SALEM'S LOT.
// SO HERE I GO IS MY SHOT.
// FEET FAIL ME NOT.
// THIS MAY BE THE ONLY OPPORTUNITY THAT I GOT.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU CAN DO ANYTHING YOU SET YOUR MIND TO, MAN.
// THE END.
// REALLY.
// THIS TIME.
// I PROMISE.
// NO MORE.
// GOODBYE.
// FOREVER.
// AMEN.
// HALLELUJAH.
// PRAISE THE LORD.
// ALLAHU AKBAR.
// OM MANI PADME HUM.
// NAMASTE.
// SHALOM.
// SALAAM.
// PEACE.
// LOVE.
// UNITY.
// RESPECT.
// ONE LOVE.
// ONE HEART.
// ONE DESTINY.
// ONE GOD.
// ONE TRUTH.
// ONE PATH.
// ONE WAY.
// ONE LIFE.
// ONE CHANCE.
// ONE SHOT.
// ONE OPPORTUNITY.
// TO SEIZE EVERYTHING YOU EVER WANTED.
// IN ONE MOMENT.
// WOULD YOU CAPTURE IT.
// OR JUST LET IT SLIP.
// YO.
// HIS PALMS ARE SWEATY.
// KNEES WEAK.
// ARMS ARE HEAVY.
// THERE'S VOMIT ON HIS SWEATER ALREADY.
// MOM'S SPAGHETTI.
// HE'S NERVOUS.
// BUT ON THE SURFACE HE LOOKS CALM AND READY.
// TO DROP BOMBS.
// BUT HE KEEPS ON FORGETTING.
// WHAT HE WROTE DOWN.
// THE WHOLE CROWD GOES SO LOUD.
// HE OPENS HIS MOUTH.
// BUT THE WORDS WON'T COME OUT.
// HE'S CHOKING NOW.
// EVERYBODY'S JOKING NOW.
// THE CLOCK'S RUN OUT.
// TIME'S UP.
// OVER.
// BLOW.
// SNAP BACK TO REALITY.
// OPE.
// THERE GOES GRAVITY.
// OPE.
// THERE GOES RABBIT.
// HE CHOKED.
// HE'S SO MAD.
// BUT HE WON'T GIVE UP THAT EASY.
// NO.
// HE WON'T HAVE IT.
// HE KNOWS HIS WHOLE BACK'S TO THESE ROPES.
// IT DON'T MATTER.
// HE'S DOPE.
// HE KNOWS THAT.
// BUT HE'S BROKE.
// HE'S SO STAGNANT.
// HE KNOWS.
// WHEN HE GOES BACK TO THIS MOBILE HOME.
// THAT'S WHEN IT'S BACK TO THE LAB AGAIN.
// YO.
// THIS WHOLE RHAPSODY.
// BETTER GO CAPTURE THIS MOMENT.
// AND HOPE IT DON'T PASS HIM.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// THE SOUL'S ESCAPING.
// THROUGH THIS HOLE THAT IS GAPING.
// THIS WORLD IS MINE FOR THE TAKING.
// MAKE ME KING.
// AS WE MOVE TOWARD A NEW WORLD ORDER.
// A NORMAL LIFE IS BORING.
// BUT SUPERSTARDOM'S CLOSE TO POST MORTEM.
// IT ONLY GROWS HARDER.
// HOMIE GROWS HOTTER.
// HE BLOWS.
// IT'S ALL OVER.
// THESE HOS IS ALL ON HIM.
// COAST TO COAST SHOWS.
// HE'S KNOWN AS THE GLOBETROTTER.
// LONELY ROADS.
// GOD ONLY KNOWS.
// HE'S GROWN FARTHER FROM HOME.
// HE'S NO FATHER.
// HE GOES HOME.
// AND BARELY KNOWS HIS OWN DAUGHTER.
// BUT HOLD YOUR NOSE.
// 'CAUSE HERE GOES THE COLD WATER.
// THESE HOS DON'T WANT HIM NO MO'.
// HE'S COLD PRODUCT.
// THEY MOVED ON TO THE NEXT MO'.
// WHO FLOWS.
// HE NOSE-DOVE AND SOLD NADA.
// SO THE SOAP OPERA IS TOLD AND UNFOLDS.
// I SUPPOSE IT'S OLD PARTNER.
// BUT THE BEAT GOES ON.
// DA-DA-DUM DA-DUM DA-DA.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// NO MORE GAMES.
// I'MA CHANGE WHAT YOU CALL RAGE.
// TEAR THIS MOTHERFUCKING ROOF OFF LIKE TWO DOGS CAGED.
// I WAS PLAYING IN THE BEGINNING.
// THE MOOD ALL CHANGED.
// I'VE BEEN CHEWED UP AND SPIT OUT AND BOOED OFF STAGE.
// BUT I KEPT RHYMING AND STEPPED RIGHT INTO THE NEXT CYPHER.
// BEST BELIEVE SOMEBODY'S PAYING THE PIED PIPER.
// ALL THE PAIN INSIDE AMPLIFIED BY THE FACT.
// THAT I CAN'T GET BY WITH MY NINE TO FIVE.
// AND I CAN'T PROVIDE THE RIGHT TYPE OF LIFE FOR MY FAMILY.
// 'CAUSE MAN, THESE GODDAMN FOOD STAMPS DON'T BUY DIAPERS.
// AND THERE'S NO MOVIE.
// THERE'S NO MEKHI PHIFER.
// THIS IS MY LIFE.
// AND THESE TIMES ARE SO HARD.
// AND IT'S GETTING EVEN HARDER TRYING TO FEED AND WATER MY SEED.
// PLUS.
// TEETER TOTTER CAUGHT UP BETWEEN BEING A FATHER AND A PRIMA DONNA.
// BABY MAMA DRAMA'S SCREAMING ON AND TOO MUCH FOR ME TO WANNA.
// STAY IN ONE SPOT.
// ANOTHER DAY OF MONOTONY.
// HAS GOTTEN ME TO THE POINT.
// I'M LIKE A SNAIL.
// I'VE GOT TO FORMULATE A PLOT.
// OR END UP IN JAIL OR SHOT.
// SUCCESS IS MY ONLY MOTHERFUCKING OPTION.
// FAILURE'S NOT.
// MOM, I LOVE YOU.
// BUT THIS TRAILER'S GOT TO GO.
// I CANNOT GROW OLD IN SALEM'S LOT.
// SO HERE I GO IS MY SHOT.
// FEET FAIL ME NOT.
// THIS MAY BE THE ONLY OPPORTUNITY THAT I GOT.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU BETTER LOSE YOURSELF.
// IN THE MUSIC.
// THE MOMENT.
// YOU OWN IT.
// YOU BETTER NEVER LET IT GO.
// YOU ONLY GET ONE SHOT.
// DO NOT MISS YOUR CHANCE TO BLOW.
// THIS OPPORTUNITY COMES ONCE IN A LIFETIME.
// YO.
// YOU CAN DO ANYTHING YOU SET YOUR MIND TO, MAN.
// THE END.
// REALLY.
// THIS TIME.
// I PROMISE.
// NO MORE.
// GOODBYE.
// FOREVER.
// AMEN.
